version: '3.4'

services:
  # db:
  #   image : mysql:8.0
  #   container_name: mysql.db
  #   volumes:
  #     - ./db/data:/var/lib/mysql              # データの永続化を行う
  #     - ./mysql/conf/:/etc/mysql/conf.d/         # 設定ファイルをここから読み込ませる
  #     - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期データを与える場合はここから読み込ませる
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_PW}       #rootパスワードの設定 PWRoot1
  #     - MYSQL_DATABASE=daysoff
  #     - TZ=Asia/Tokyo

  pdf_django:
    image: pdf-django:latest
    build:
      context: .
    #  dockerfile: ./Dockerfile-debug
    #  command: bash -c export DUID=$(id -u); docker build -f ./Dockerfile-debug -t daysoff-debug:latest --build-arg DUID=$DUID .
    container_name: pdf-django
    #command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading"]
    #command: ["uwsgi", "--ini", "/app/daysoff/daysoffapp/uwsgi.ini"]
    volumes:
      - ./src:/app
      - ./static:/static
    #  - ./log/uwsgi/:/var/log/uwsgi
    ports:
      - 8000:8000
    #  - 8001:8001   # uwsgi ポート
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # depends_on:
    #   - db

